# Generated by Django 4.2.5 on 2023-09-12 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 9, 12, 5, 8, 59, 997367, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
