# 1 워크플로의 이름 지정
name: CI
# 2 워크플로가 시작될 조건 지정
on:
  push:
    branches: [ deploy ]
jobs:
  deploy:
    runs-on: ubuntu-latest # 3 실행 환경 지정
    #4 실행스텝지정
    steps:
    - name: Checkout 코드
      uses: actions/checkout@v2
      
    - name: 설정 SSH 키
      run: |
        mkdir -p ~/.ssh
        echo "$MDM_WAS_KEY" > ~/.ssh/id_rsa
        if [ -f ~/.ssh/id_rsa ]; then
          echo "SSH private key file exists"
        else
          echo "SSH private key file does not exist"
        fi
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 43.201.204.254 >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/id_rsa ubuntu@43.201.204.254 "echo SSH 접속 성공"


    - name: 원격 명령 실행
      run: |
        # 원격 서버에 명령 실행 (예: 배포 스크립트 실행)
        # Git 레포지토리 업데이트
        cd /home/ubuntu/temp/django_tutorial
        git pull
    
        # Docker 이미지 빌드
        docker build -t ci_test:latest .
    
        # 현재 실행 중인 Docker 컨테이너 중지
        docker stop ci_test || true
        docker rm ci_test || true
    
        # 새로운 이미지로 Docker 컨테이너 시작
        docker run -d -p 90:90 --name ci_test ci_test:latest

