# 1 워크플로의 이름 지정
name: CI
# 2 워크플로가 시작될 조건 지정
on:
  push:
    branches: [ deploy ]
jobs:
  deploy:
    runs-on: ubuntu-latest # 3 실행 환경 지정
    #4 실행스텝지정
    steps:
    - name: Checkout 코드
      uses: actions/checkout@v2

    - name: SSH로 외부 서버에 접속하여 컨테이너 업데이트
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop dj-tt || true
          docker rm dj-tt || true
          docker build -t dj-tt .
          docker run --privileged -p 8001:8001  --name dj-tt dj-tt

