# 1 워크플로의 이름 지정
name: CI
# 2 워크플로가 시작될 조건 지정
on:
  push:
    branches: [ deploy ]
jobs:
  deploy:
    runs-on: ubuntu-latest # 3 실행 환경 지정
    #4 실행스텝지정
    steps:
    - name: Checkout 코드
      uses: actions/checkout@v2
      
    - name: 설정 SSH 키
      env:
        MDM_WAS_KEY: ${{ secrets.MDM_WAS_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$MDM_WAS_KEY" > ~/.ssh/id_rsa.pem
        chmod 600 ~/.ssh/id_rsa.pem
        ssh-keyscan 43.201.204.254 >> ~/.ssh/known_hosts

    - name: SSH로 외부 서버에 접속하여 컨테이너 업데이트
      uses: appleboy/ssh-action@master
      with:
        host: 43.201.204.254
        username: ubuntu
        key: ${{ secrets.MDM_WAS_KEY }}
        script: |
          pwd
          sudo docker ps

#    - name: 원격 명령 실행
#      run: |
#        ssh -i ~/.ssh/id_rsa.pem ubuntu@43.201.204.254
#
#        pwd
#        sudo docker ps

